### ISSUE TITLE
Warn on outdated brosers

### ISSUE THREAD

**Issue by konstin** [meine-stadt-transparent/meine-stadt-transparent#14]
In our sector it's unfortunately quite common that users have dangerously outdated browsers. We should warn about them about that with a big red sign.

**Comment by CatoTH** [comment]
Halte ich ehrlich gesagt wenig davon. Die meisten derjenigen, die veraltete Browser einsetzen, machen das deshalb, weil es die Firmenrichtlinie so sagt und sie gar nicht die Möglichkeit haben. Da hilft kein Hinweis, der nervt dann nur. Bei den Privatrechnern dagegen ist schon längst bei allen Browsern ein Auto-Update die Norm, und gegen die sieben gleichzeitig installierten Spyware-Toolbars und Windows-Trojaner, die bei Privat-PCs das Problem sind, können wir nichts machen, weil wir das gar nicht erst abfragen können. Das einzige wäre ein "kauf die ein neues Android-Gerät, dein aktuelles hat seit einem Jahr keine Sicherheitsupdates mehr", aber das find ich auch wenig prickelnd.
Das sehe ich ehrich gesagt nicht als unsere Aufgabe an. Die Zeiten, wo man die Leute vor einem IE6 warnen muss, sind vorbei.

**Comment by CatoTH** [comment]
und nachdem wir auf Flexbox setzen, können wir ja eh davon ausgehen, dass unsere Seite auf allen Browsern < IE10 kaputt ist ^^
