### ISSUE TITLE
Übersetzungen

### ISSUE THREAD

**Issue by konstin** [meine-stadt-transparent/meine-stadt-transparent#18]
Alles auf Deutsch übersetzen

**Comment by CatoTH** [comment]
Entscheidungen:
- Anrede: Sie / Du?
- Form der geschlechtergerechten Anrede (Camel-case, Snake-case, Sternchen, ...)

**Comment by CatoTH** [comment]
- Organizations (Fraktionen, Ausschüsse, evtl. Dienststellen / Referate): wie heißt der Menüpunkt dazu? "Gremien"?

**Comment by akuckartz** [comment]
"Gremien" wird regelmäßig am besten passen. 'Paper" sind Vorlagen, darunter Beschlussvorlagen, Mitteilungsvorlagen u.dgl.
