### ISSUE TITLE
Zooming and scrolling in embedded maps, google style

### ISSUE THREAD

**Issue by konstin** [meine-stadt-transparent/meine-stadt-transparent#183]
I've seen a google maps embedded map, where scrolling wouldn't zoom, but show a "press shift to zoom" overlay. Unfortunately I forgot where I found that. We should implement that as alternative and test with users which works better.

**Comment by CatoTH** [comment]
That's with all embedded google maps. It sucks. As discussed back then, it requires you using the keyboard + the mouse to use the map, plus when just scrolling over the map, the whole map suddenly gets dark. The only reason to do that would be to assume that many people have learned it that way from those embedded google maps, though I'm not sure anyone has ever actually used that kind of navigation. Probably everyone uses the Plus/Minus-Sign to zoom instead.

**Comment by konstin** [comment]
ah well then let's keep it how it is
