### ISSUE TITLE
Alternative Dokumentenanzeige

### ISSUE THREAD

**Issue by konstin** [meine-stadt-transparent/meine-stadt-transparent#21]
Wir sollten zumindest die Möglichkeit einbauen, Bilder anzuzeigen, und einen guten Fallback für sonstige Dateitypen haben.

**Comment by CatoTH** [comment]
TIFF, das bei München Transparent leider gelegentlich vorkommt, ist deutlich schwerer zu unterstützen, da man hier die Bilder konvertieren müsste, um sie im Browser anzuzeigen. Das spar ich mir deshalb mal.

**Comment by konstin** [comment]
Seh ich genauso.
