### ISSUE TITLE
Datumssortierung verbessern

### ISSUE THREAD

**Issue by CatoTH** [meine-stadt-transparent/meine-stadt-transparent#31]
Problem bei der Datumssortierung:
- Im längerfristigen Betrieb dürfte wahrscheinlich das modified-Feld relevanter sein als das legal_date, u.a. da nicht alle Datenobjekte ein legal_date haben
- modified ist aber erst ab dem Zeitpunkt sinnvoll, wann die Erstindizierung abgeschlossen ist.

Vorschlag:
 Es gibt eine setzbare Django-Setting "Erstindizierung" und in Elasticsearch ein zusätzliches Feld sort_date. Wenn das modified neuer ist als die Erstindizierung, zählt modified. Wenn älter, dann abhängig vom Datentyp: legal_date wenn vorhanden, ansonsten Zeitpunkt der Erstindizierung. (Ergebnis wäre: bei Sortierung nach Datum würden Personen, Gremien etc. zu dem Zeitpunkt der Erstindizierung einsortiert werden. Alternative wäre: sort_datum auf null setzen, sprich dass sie gar nicht / nur am Schluss auftauchen)

**Comment by konstin** [comment]
Ich vermute, dass created besser funktioniert als modified. Mit created wären wir auch gegen Änderung abgesichert, bei denen in einem OParl-Server einmal alle modified Werte aktualisiert werden

**Comment by CatoTH** [comment]
Ist jetzt created, und ein Skript um das "created" nach dem initialen Import auf "legal_date" zu setzen (bzw. einen Dummy-Wert für die wenige Fälle, wo es kein legal_date gibt)

**Comment by CatoTH** [comment]
Siehe https://github.com/meine-stadt-transparent/meine-stadt-transparent/commit/e4af3d139d4d767bf72244cef69911a1afc3753a#commitcomment-26700308 - Extra-Feld (date_sorting)

**Comment by konstin** [comment]
Das Feld kann dann auch in elasticsearch verwendet werden, auch wenn die elasticsearch-Integration nicht ganz so wichtig ist.
