### ISSUE TITLE
Choose language independent from browser locale

### ISSUE THREAD

**Issue by jahnique** [meine-stadt-transparent/meine-stadt-transparent#340]
Currently the language of Meine Stadt Transparent is defined by the language configured in the user's browser. However, some people prefer surfing on a website in German regardless the browser's settings.

Thus it'd be great to have a language selector integrated into the header of the website.

**Comment by ubergesundheit** [comment]
This would be awesome to have for the Münster instance!

**Comment by konstin** [comment]
Since the content is monolingual anyway, would it make sense to just set a single language regardless of the browser settings?

**Comment by ubergesundheit** [comment]
Even though the documents are probably all in german, I think having the interface available in other languages would help non german speakers.

**Comment by scoid** [comment]
> Even though the documents are probably all in german, I think having the interface available in other languages would help non german speakers.

We have more than 50 languages in our small town. It would be wonderful if the user interface could at least simplify access to information. 

Anyone who has ever had to find their way around a foreign country understands that this is a small shortcut before struggling through the text of the language of the host country or new home.

**Comment by konstin** [comment]
I've set the language now to german by default (ignoring the browser locale), and i've added a language switcher for comprehensiveness. Given the legal German vernacular that is used in all the documents that is even hard to understand for actual native speakers, i'd be surprised if anybody with not at least a near-native german language would be using the site, except through google translate directly

**Comment by ubergesundheit** [comment]
> I've set the language now to german by default (ignoring the browser locale), and i've added a language switcher for comprehensiveness.

nice! Once this is available in a release, can you close this issue?

**Comment by konstin** [comment]
it's already live :)
