### ISSUE TITLE
Add link to website into the iCal entries

### ISSUE THREAD

**Issue by agrippine314** [meine-stadt-transparent/meine-stadt-transparent#384]
Hi
I use the iCal integration (in my case into Outlook, I assume it's similar in other calendar clients). It is very helpful to get an idea when something is happening.
But it would be even better if the calendar entry contained a hyperlink to the corresponding "meine-stadt-transparent" calendar entry so that I can quickly access the agenda details or see that they are still missing, without navigating there through the web site.

F.ex. the calendar entry of May 28 in Landshut would contain the following link: https://landshut-transparent.de/meeting/32/.

Thanks :-)
Annette

**Comment by konstin** [comment]
Thanks for the suggestion! I've added the url as part of the description. The images below show how this looks like for google calendar and outlook online:

![grafik](https://user-images.githubusercontent.com/6826232/83778434-04d5b200-a68b-11ea-8faa-0cc84e47d933.png)

![grafik](https://user-images.githubusercontent.com/6826232/83778475-0ef7b080-a68b-11ea-908e-6915ad8640b3.png)

There is a way to specify a url in ics files, however all calendars I've tried seem to ignore that value; I just made it part of the html description now.
