### ISSUE TITLE
Nicht geänderte Objekte nicht aktualisieren

### ISSUE THREAD

**Issue by CatoTH** [meine-stadt-transparent/meine-stadt-transparent#41]
Aktuell scheinen z.B. bei den Files bei jedem Import immer alle Dateien neu eingelesen zu werden. Im Code scheint mir zwar eine Variable ``do_update`` angelegt, aber nicht weiter berücksichtigt zu werden. Schaust du dir das mal an?

**Comment by konstin** [comment]
Ja, da hatte ich tatsächlich den Parameter übersehen (und noch ein paar andere Fehler, die jetzt auch mit abgetestet werden).
