### ISSUE TITLE
Titel im Importer verbessern

### ISSUE THREAD

**Issue by konstin** [meine-stadt-transparent/meine-stadt-transparent#48]
Z.B. indem bei Dateinamen `Sitzungsvorlage \((.*)\)` nach  `$1` umgeschrieben wird, wenn die Vorlage schon passend heißt.

Dafür sollte eine recht allgemeine Lösung gebaut werden, die die Regeln aus einer Konfigurationsdatei liest. Das hat aber keine hohe Priorität, da die jetzigen Titel und Namen an sich korrekt sind, wenn auch nicht schön.

**Comment by CatoTH** [comment]
@konstin Da wäre vor allem die Entscheidung, wo man das am besten hinterlegt. Es geht ja wahrscheinlich um eine Liste an festlegbaren Regexp-Befehlen. Das ließe sich in JSON-Format in .env hinterlegen - geht, aber nur mäßig schön. Das dict-Modul von environ ist leider nicht so toll, da dann Kommas und Gleichheitszeichen gesperrt sind. Ansonsten könnte man noch die Möglichkeit geben, irgendwo explizit ein custom-Python-Skript zu hinterlegen.

**Comment by konstin** [comment]
Ich würde eine extra json Datei nehmen. Vllt. kann man die dann auch zu den Customizations tun.

**Comment by CatoTH** [comment]
Ich hab das jetzt über eine Pyton-Datei gelöst, mit der man im customizations-Ordner Hooks definieren kann. Das hab ich auch gleich für die Personen eingebaut, damit da das "Herr"/"Frau" auch gleich beim Import herausgeschnippselt wird.
https://github.com/meine-stadt-transparent/meine-stadt-transparent#customizations-sanitizing-values-coming-from-an-oparl-api

Ich lass das gleich mal noch auf dem Server laufen...
