### ISSUE TITLE
Bug im Query-String-Handling

### ISSUE THREAD

**Issue by konstin** [meine-stadt-transparent/meine-stadt-transparent#49]
Aus https://meine-stadt-transparent.de/search/query/after:2018-01-01%20before:2018-01-31%20after:2001-01-01%20open%20source/ sollte das doppelte after entfernt werden

**Comment by CatoTH** [comment]
Wie kommt man denn auf so einen Link?

**Comment by konstin** [comment]
Indem man `after:2001-01-01` in das Textfeld eingibt.
