### ISSUE TITLE
More search filter

### ISSUE THREAD

**Issue by konstin** [meine-stadt-transparent/meine-stadt-transparent#5]
- [x] Person
 - [x] Any organization 
 - [ ] Sort by: Best Match | Newest first | Oldest first

**Comment by CatoTH** [comment]
Bei den Organisationen haben wir noch das Problem, dass die Relationen aktuell noch nicht befüllt werden, also insb. die Paper/Organization-Relation. Aktuell werden daher nur Personen gefunden, was aber wohl nicht das ist, was man bei der Funktion eigentlich erwartet...

**Comment by konstin** [comment]
Ich würde das mit den Dummy-Daten testen und darauf hoffen, dass eine der noch kommenden Schnittstellen die Relation noch ordentlich erfasst.

**Comment by CatoTH** [comment]
Folgeticket zur Verfeinerung der Datumssortierung: #31
