### ISSUE TITLE
Kalender-Export / abonnieren

### ISSUE THREAD

**Issue by CatoTH** [meine-stadt-transparent/meine-stadt-transparent#55]
Es sollten nicht nur einzelne Termine per iCal abrufbar sein, sondern auch der komplette Kalender abonnierbar - damit man neue Termine automatisch im Kalender bekommt. Sollte dank der Vorarbeit beim Einzel-Termin-Export ziemlich simpel einzurichten sein.

**Comment by konstin** [comment]
Also quasi `committee_ical` nur für alle Gremien, oder?

**Comment by CatoTH** [comment]
Ja genau. Macht natürlich nur bei so kleinen Kommunen Sinn. ``committee_ical``, ist das eigentlich irgendwo eingebunden? Oder bringt es das hier eh noch nicht, weil es die Gremien/Meeting-Zuordnung (noch) nicht gibt?

**Comment by konstin** [comment]
Das hängt unter `^organization/(?P<pk>[0-9]+)/ical/$`, es gibt aber noch
keinen Button in der UI. Die Verlinkung meeting <-> organization macht
der Importer außerdem noch nicht.

**Comment by konstin** [comment]
Damit das ganze nicht explodiert (und weil allein die 500 Termine von Jülich gute 3 Sekunden zum erzeugen brauchen), habe ich den Export auf 3 Monate um das aktuelle Datum eingeschränkt. Evtl. sind auch 6 Monate besser oder wir machen eine Option draus.

**Comment by konstin** [comment]
Ah ja, und in den Organisationen ist auch der zugehörige iCal Export verlinkt
