### ISSUE TITLE
Disclaimer bei den Files

### ISSUE THREAD

**Issue by CatoTH** [meine-stadt-transparent/meine-stadt-transparent#60]
Zu diskutieren: Bei den Files sollte es irgendeinen Hinweis darauf geben, dass die nicht bei uns liegen (allenfalls gecachet), sondern vom jeweiligen RIS kommen und wir damit nur eingeschränkt haftbar dafür sind.

**Comment by akuckartz** [comment]
Das RIS sollte genaue Informationen zu Nutzungsrechten liefern.
