### ISSUE TITLE
CSP prohibited inline styles

### ISSUE THREAD

**Issue by stv0g** [meine-stadt-transparent/meine-stadt-transparent#759]
https://github.com/meine-stadt-transparent/meine-stadt-transparent/blob/216d12507eba09889f4685f430247e7e3a3fb843/mainapp/templates/account/home.html#L22

`Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.`

**Comment by konstin** [comment]
Good catch!
