### ISSUE TITLE
Feature Liste zum readme hinzufügen

### ISSUE THREAD

**Issue by gerbsen** [meine-stadt-transparent/meine-stadt-transparent#78]
Hallo nochmal,
Ihr habt ja den ganzen Installations und Anpassungsprozess super dokumentiert. Was mir auf den ersten Blick jetzt noch fehlt ist eine Liste mit Features was *meine-stadt-transparent* eigentlich so alles kann. Hab ich nur nicht gründlich genug geschaut?

Viele Grüße,
Daniel

**Comment by CatoTH** [comment]
Ich hab hier mal etwas aufgesetzt: https://github.com/meine-stadt-transparent/meine-stadt-transparent#about-this-project
Weitere Informationen gibt es natürlich auch noch auf deutsch unter https://meine-stadt-transparent.de/info/about/
