### ISSUE TITLE
Automagic reparieren

### ISSUE THREAD

**Issue by CatoTH** [meine-stadt-transparent/meine-stadt-transparent#85]
Ich hab es nicht geschafft, den "Automagic-Import" anzuwenden:
```bash
./manage.py import Jülich
# Exception: Could not find anything for 'Jülich'
```
Vermutlich weil es Jülich in https://dev.oparl.org/api/endpoints nicht gibt.
```bash
./manage.py import München

# File ".../meine-stadt-transparent/importer/oparl_auto.py", line 130, in get_endpoint_from_cityname
#    return endpoint[1]["oparl_id"], endpoint[0]["id"]
#KeyError: 'oparl_id'
```
Evtl. hat sich das JSON der Schnittstelle geändert?

**Comment by konstin** [comment]
Ich nehme jetzt einfach noch den OParl Mirror dazu, der hat Jülich drinnen. Und es heißt jetzt auch nicht mehr automagic, sondern einfach nur noch import ;)
