### ISSUE TITLE
PGP im Stil von selbstauskunft.net ausprobieren

### ISSUE THREAD

**Issue by konstin** [meine-stadt-transparent/meine-stadt-transparent#88]
Ich will mir mal anschauen, wie viel Aufwand es ist, eine PGP-Funktion im Stil  https://blog.selbstauskunft.net/2010/05/pgp-gnupg-unterstuetzung/ umzusetzen.

**Comment by akuckartz** [comment]
Ist das umgesetzt oder war es zu viel Aufwand?

**Comment by konstin** [comment]
Die Kurzfassung ist, dass ich das zwar komplett implementiert habe, PGP in der Praxis aber so grottenschlecht ist, dass das jetzt per default ausgeschaltet ist.
